server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_reservation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: airline
    password: vipul73384
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      expiration: 86400000 # 24 hours

logging:
  level:
    com.skywings: DEBUG
    org.springframework.security: DEBUG